.386
DATA SEGMENT USE16
A1 DW 11
B1 DW 23
C1 DW 13
D1 DW 41
E1 DW 0
F1 EQU 55
DATA ENDS
STACK SEGMENT USE16 STACK
    DB 200 DUP(?)
STACK ENDS
CODE SEGMENT USE16
    ASSUME DS:DATA, SS:STACK, CS:CODE
START: MOV AX, DATA
       MOV DS, AX
       MOV AX, A1
       ADD AX, B1
       SUB AX, C1
       SAR AX, 3
       IMUL AX, F1
       ADD AX, D1
       MOV E1, AX
       MOV AH, 4CH
       INT 21H
CODE ENDS
    END START